# workflow name
name: test

# a push triggers this workflow
on: [push]


# a workflow run is made up of one or more jobs
jobs:
  # a job_id
  foo_job:
    name: first job
    runs-on: ubuntu-latest
    # environment vars inside this job (and each step)
    # note: changes to environment are not shared between steps
    env:
      FOO: Baaaz

    
    # a job contains a sequence of steps that should run ()
    # note: not all steps run actions, but all actions run as a step
    steps:
      # First of all, we clone the repo using the checkout action.
      - name: Checkout
        uses: actions/checkout@master
 
      - name: echo some stuff
        run: |
          echo Hello First Workflow FOO is $FOO.

      # We use the arduino/setup-arduino-cli action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
 
      # We then install the platform, which one will be determined
      # dynamically by the build matrix.
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:samd
          arduino-cli core install esp8266:esp8266
          arduino-cli core list

      # - name: Download CLI
      #   uses: Legion2/download-release-action@v2.1.0
      #   with:
      #     repository: Makuna/NeoPixelBus
      #     tag: '2.5.3'
      #     path: libraries
      #     file: NeoPixelBus-2.5.3.zip

      - name: Build all example sketches
        uses: antimatter15/esp8266-arduino-builder-action@v4.0.0

#   with:
#     # Path to a single sketch
#     sketch: # optional

#     # Directory in which to search for sketches
#     sketchDirectory: # optional, default is examples

#     # Fully Qualified Board Name
#     board: # optional, default is arduino:avr:uno

#     # Directory containing Arduino libraries. Use this directory to install required 3rd-party libraries.
#     libraries: # optional, default is libraries
#     #    <NeoPixelBus.h>
#     #    <NeoPixelAnimator.h>
#     #    <ESP8266WiFi.h>
#     #    <Wire.h>
#     #    <LiquidCrystal_I2C.h>

#     # Directory containing Arduino platforms
#     hardware: # optional, default is hardware

